### ISSUE TITLE
librashader-spirv-cross has been yanked

### ISSUE THREAD

**Issue by GPHemsley** [SnowflakePowered/librashader#111]
All versions of librashader-spirv-cross have been yanked (apparently in favor of spirv-cross2 instead of spirv-cross), which means librashader no longer builds.

**Comment by GPHemsley** [comment]
A workaround, for those who need it:
```toml
[patch.crates-io]
librashader-spirv-cross = { git = "https://github.com/chyyran/spirv_cross.git", rev = "3c11426a9055232e349c25dcf2a03e94512dbe88" }
```
